const items = [
    {
        id: '001',
        image: 'C:/image/a.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 may 2026',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'C:/image/b.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '1 march 2026',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'C:/image/c.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '20 Oct 2026',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'C:/image/d.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '26 jan 2026',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'C:/image/e.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '26 dec 2026',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'C:/image/f.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 feb 2026',
        rating: {
            stars: 3.0,
            count: 99,
        },
    },
    {
        id: '007',
        image: 'C:/image/g.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        delivery_date: '17 feb 2026',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'C:/image/h.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '1 feb 2026',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: 'C:/image/i.jpeg',
        company: 'X30',
        item_name: 'black shirt',
        original_price: 2999,
        current_price: 1499,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 feb 2026',
        rating: {
            stars: 4.5,
            count: 120,
        },
    },
    {
        id: '010',
        image: 'C:/image/k.jpeg',
        company: 'Oysho',
        item_name: 'gay boy',
        original_price: 2999,
        current_price: 1499,
        discount_percentage: 5,
        return_period: 14,
        delivery_date: '10 feb 2026',
        rating: {
            stars: 4.5,
            count: 12000,
        },
    },
    {
        id: '011',
        image: 'C:/image/l.jpeg',
        company: 'Jaykunj',
        item_name: 'aesthic ka 14',
        original_price: 2999,
        current_price: 2499,
        discount_percentage: 44,
        return_period: 14,
        delivery_date: '5 feb 2026',
        rating: {
            stars: 4.5,
            count: 1210,
        },
    },
    {
        id: '012',
        image: 'C:/image/m.jpeg',
        company: 'ritik',
        item_name: 'Gym ka 14',
        original_price: 2999,
        current_price: 1999,
        discount_percentage: 8,
        return_period: 14,
        delivery_date: '19 feb 2026',
        rating: {
            stars: 4.5,
            count: 1220,
        },
    },
];